/**
 * ERC-8021 Builder Code Attribution
 *
 * Uses the official `ox` library to generate the data suffix appended
 * to transaction calldata for Base Builder Rewards attribution.
 *
 * @see https://docs.base.org/base-chain/builder-codes/builder-codes
 * @see https://www.erc8021.com
 */
import { Attribution } from 'ox/erc8021';
import { type Hex } from 'viem';

/** The ERC-8021 attribution suffix generated by ox */
export const BUILDER_CODE_SUFFIX: Hex = Attribution.toDataSuffix({
  codes: ['bc_p9yskkfh'],
});
