const SECONDS_IN_MINUTE = 60
const MINUTES_IN_HOUR = 60
const HOURS_IN_DAY = 24
export const ONE_SECOND_MS = 1000
const ONE_MINUTE_MS = SECONDS_IN_MINUTE * ONE_SECOND_MS
const ONE_HOUR_MS = MINUTES_IN_HOUR * ONE_MINUTE_MS
export const ONE_DAY_MS = HOURS_IN_DAY * ONE_HOUR_MS
export const MAX_REACT_QUERY_CACHE_TIME_MS = ONE_DAY_MS * 24
